version: '3.4'

services:
  dankdomain:
    image: bidmc-its-xterm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
