version: '3.4'

services:
  bidmc-its-xterm:
    image: bidmc-its-xterm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
